server:
  port: 8085
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserService
    username: neebal
    password: Neebal#1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5InnoDBDialect
         
        #dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: User-Service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:8761/eureka

     

    
    
    